#!/usr/bin/env python3
"""Inject the final-quiz band + button into a course landing page.

Idempotent: re-running replaces the generated block rather than stacking copies.
Uses quiz_lib as the one reader. Bumps the ?v= cache token on every css change,
per the estate rule.

  python3 inject_button.py <repo> --set leader=<formUrl> --set builder=<formUrl>
  python3 inject_button.py <repo> --placeholder     # local preview, dead links
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import quiz_lib as Q  # noqa: E402

CSS_START = "/* ==== FINAL QUIZ - generated by quiz-system, do not hand-edit ==== */"
CSS_END = "/* ==== end FINAL QUIZ ==== */"
HTML_START = "  <!-- ==== FINAL QUIZ - generated by quiz-system, do not hand-edit ==== -->"
HTML_END = "  <!-- ==== end FINAL QUIZ ==== -->"

CSS = CSS_START + """
.finalquiz {
  background: var(--indigo-50);
  border: 1px solid var(--indigo-soft);
  border-radius: 22px;
  padding: 34px 34px 30px;
}
.finalquiz .section-kicker { margin-bottom: 6px; }
.fq-lede { max-width: 62ch; line-height: 1.85; margin: 0 0 18px; }
.fq-facts { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 22px; }
.fq-actions { display: flex; flex-wrap: wrap; gap: 12px; }
.fq-btn { font-size: 1.02rem; padding: 14px 26px; border-radius: 999px; }
.fq-note { margin: 18px 0 0; font-size: .9rem; color: var(--muted); line-height: 1.7; }
.fq-btn[href="#"] { opacity: .45; pointer-events: none; }
@media (max-width: 620px) {
  .finalquiz { padding: 26px 20px 24px; }
  .fq-actions { flex-direction: column; align-items: stretch; }
  .fq-btn { text-align: center; }
}
""" + CSS_END

TRACK_BTN = '    <a class="btn primary fq-btn" href="{url}" target="_blank" rel="noopener">{label}</a>'


def band_html(quiz: dict) -> str:
    tracks = quiz["tracks"]
    buttons = []
    for name, t in tracks.items():
        url = t.get("formUrl") or "#"
        if name == Q.TRACK_SINGLE:
            label = "Take the final quiz →"
        else:
            label = f"Final quiz · {t.get('label', name)} →"
        buttons.append(TRACK_BTN.format(url=url, label=label))

    pick = ("" if len(tracks) == 1 else
            " Pick the track you actually attended.")
    return "\n".join([
        HTML_START,
        '  <section class="section finalquiz" id="final-quiz">',
        '    <div class="section-kicker">',
        '      <span class="klabel">Required</span>',
        '      <h2>Final quiz 🎓</h2>',
        '    </div>',
        '    <p class="fq-lede">Ten questions across the whole course, auto-scored the moment you '
        'submit, with the reasoning shown for every answer. Everyone who attends completes this.'
        + pick + '</p>',
        '    <div class="fq-facts">',
        '      <span class="pill light">10 questions</span>',
        '      <span class="pill light">80% to pass</span>',
        '      <span class="pill light">about 8 minutes</span>',
        '      <span class="pill light">unlimited retakes</span>',
        '    </div>',
        '    <div class="fq-actions">',
        *buttons,
        '    </div>',
        '    <p class="fq-note">Sign in with your work account so your completion is recorded. '
        'Below the bar? Read the explanations and take it again, only your best attempt counts.</p>',
        '  </section>',
        HTML_END,
        "",
    ])


def replace_block(text: str, start: str, end: str, block: str) -> str:
    if start in text and end in text:
        head = text[: text.index(start)]
        tail = text[text.index(end) + len(end):]
        return head + block + tail
    return text


def inject_css(repo: Path) -> bool:
    css_path = repo / "assets" / "style.css"
    css = css_path.read_text(encoding="utf-8")
    if CSS_START in css:
        new = replace_block(css, CSS_START, CSS_END, CSS)
    else:
        new = css.rstrip() + "\n\n" + CSS + "\n"
    if new == css:
        return False
    css_path.write_text(new, encoding="utf-8")
    return True


def bump_version(repo: Path) -> int:
    """Bump every ?v=N cache token across the repo's html. Returns the new version."""
    pages = list(repo.glob("*.html")) + list((repo / "courses").glob("*.html"))
    versions = set()
    for p in pages:
        versions.update(int(m) for m in re.findall(r"\?v=(\d+)", p.read_text(encoding="utf-8")))
    new = (max(versions) if versions else 0) + 1
    for p in pages:
        src = p.read_text(encoding="utf-8")
        out = re.sub(r"\?v=\d+", f"?v={new}", src)
        if out != src:
            p.write_text(out, encoding="utf-8")
    return new


def inject_page(repo: Path, quiz: dict) -> bool:
    idx = repo / "index.html"
    src = idx.read_text(encoding="utf-8")
    block = band_html(quiz)
    if HTML_START in src:
        out = replace_block(src, HTML_START, HTML_END, block.rstrip("\n"))
    else:
        anchor = '  <footer class="pagefoot">'
        if anchor not in src:
            raise SystemExit(f"{idx}: no <footer class=\"pagefoot\"> anchor found")
        out = src.replace(anchor, block + "\n" + anchor, 1)
    if out == src:
        return False
    idx.write_text(out, encoding="utf-8")
    return True


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("repo")
    ap.add_argument("--set", action="append", default=[], metavar="track=url",
                    help="write a live form URL into final-quiz.json before injecting")
    ap.add_argument("--placeholder", action="store_true",
                    help="allow injection with empty formUrl (local preview only)")
    args = ap.parse_args()

    repo = Path(args.repo).resolve()
    qp = Q.quiz_path(repo)
    if not qp.exists():
        raise SystemExit(f"no {qp}")
    quiz = Q.load(qp)

    for pair in args.set:
        track, _, url = pair.partition("=")
        if track not in quiz["tracks"]:
            raise SystemExit(f"unknown track {track!r}, have {list(quiz['tracks'])}")
        quiz["tracks"][track]["formUrl"] = url
    if args.set:
        qp.write_text(json.dumps(quiz, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    problems = Q.validate(quiz, Q.harvest_repo(repo))
    if problems:
        raise SystemExit("quiz does not validate:\n  " + "\n  ".join(problems))

    missing = [t for t, d in quiz["tracks"].items() if not d.get("formUrl")]
    if missing and not args.placeholder:
        raise SystemExit(
            f"no formUrl for track(s): {', '.join(missing)}. "
            "Run the Quiz Factory first, then pass --set track=<url>, "
            "or use --placeholder for a local preview.")

    css_changed = inject_css(repo)
    page_changed = inject_page(repo, quiz)
    version = bump_version(repo) if css_changed or page_changed else None
    print(f"{repo.name}: css={'updated' if css_changed else 'unchanged'} "
          f"page={'updated' if page_changed else 'unchanged'} "
          f"assets bumped to ?v={version}" if version else f"{repo.name}: no change")


if __name__ == "__main__":
    main()
